// <auto-generated />
using System;
using ContactsListSoulinthavong.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactsListSoulinthavong.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20210619021952_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactsListSoulinthavong.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            EmailAddress = "imarquezlopez@bankerstrust.com",
                            FirstName = "Iridian",
                            LastName = "Lopez",
                            PhoneNumber = 5151234567L
                        },
                        new
                        {
                            ContactId = 2,
                            EmailAddress = "jsoulinthavong@yahoo.com",
                            FirstName = "Jason",
                            LastName = "Soulinthavong",
                            PhoneNumber = 5159876543L
                        },
                        new
                        {
                            ContactId = 3,
                            EmailAddress = "nellie.soul@gmail.com",
                            FirstName = "Penelope",
                            LastName = "Soulinthavong",
                            PhoneNumber = 5150001111L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
